version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - build